name: Dev build - Windows

on:
  push:
    branches:
    - dev
  pull_request:
    branches: 
    - dev

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ["7.0.x"]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Code SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build package sources
      run: dotnet build -c Release --no-restore
    - name: Build samples
      run: dotnet build ./examples/solution.sln
    - name: Test
      run: dotnet test --no-restore --collect:"XPlat Code Coverage"
    - name: Publish code coverage
      uses: codecov/codecov-action@v1
      with:
        files: "**/coverage.cobertura.xml"
        flags: unittests
        name: vertical-spectreconsolelogger-codecov
